name: Run Django Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  run-django-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests with Coverage
      working-directory: src
      run: |
        pip install coverage
        coverage run --branch --omit=manage.py,test*.py manage.py test
        # generate coverage report
        coverage report -m --skip-covered --skip-empty
        # write report to xml data
        coverage xml --skip-empty -o coverage.xml
    - name: Get Cover 
      uses: orgoro/coverage@v3.2
      if: ${{ github.event_name == 'pull_request' }}
      with:
          coverageFile: src/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
